/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommentaryIndexRouteImport } from './routes/commentary.index'
import { Route as CommentarySlugRouteImport } from './routes/commentary.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentaryIndexRoute = CommentaryIndexRouteImport.update({
  id: '/commentary/',
  path: '/commentary/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentarySlugRoute = CommentarySlugRouteImport.update({
  id: '/commentary/$slug',
  path: '/commentary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commentary/$slug': typeof CommentarySlugRoute
  '/commentary/': typeof CommentaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commentary/$slug': typeof CommentarySlugRoute
  '/commentary': typeof CommentaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commentary/$slug': typeof CommentarySlugRoute
  '/commentary/': typeof CommentaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/commentary/$slug' | '/commentary/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/commentary/$slug' | '/commentary'
  id: '__root__' | '/' | '/commentary/$slug' | '/commentary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommentarySlugRoute: typeof CommentarySlugRoute
  CommentaryIndexRoute: typeof CommentaryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commentary/': {
      id: '/commentary/'
      path: '/commentary'
      fullPath: '/commentary/'
      preLoaderRoute: typeof CommentaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commentary/$slug': {
      id: '/commentary/$slug'
      path: '/commentary/$slug'
      fullPath: '/commentary/$slug'
      preLoaderRoute: typeof CommentarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommentarySlugRoute: CommentarySlugRoute,
  CommentaryIndexRoute: CommentaryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
